services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
    # 参考 https://hub.docker.com/_/mysql 的 Environment Variables 段落
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: boss